### ISSUE TITLE
option to play remote videos through mpv

### ISSUE THREAD

**Issue by japhir** [yuchen-lea/org-media-note#10]
It would be great if this package would support playing remote videos as well, does it do that currently?

So far I've been able to play remote videos with the following:

```elisp
  (emms-play-url "https://youtu.be/AALYPv5xSos")
```
it would be perfect if I could `[[video:https://youtu.be/AALYPv5xSos]]`

**Comment by yuchen-lea** [comment]
Yeah, it's a common feature request and already discussed here: https://www.reddit.com/r/orgmode/comments/lhbv1c/ann_orgmedianote_taking_notes_when_watching/gmytd3u?utm_source=share&utm_medium=web2x&context=3

However, since:
1. it's not my need
2. I have some problem when webstreaming by mpv, and because of GFW, some websites, including youtube, cannot be accessed stably. 
3. I have to investigate how to keep the behavior of online videos consistent with local videos: insert timestamp and A-B loop link, jump to the correct position…… and there're so many different video platforms.

It would take time, but if there are any progress, I will publish here.

**Comment by yuchen-lea** [comment]
After some investigation, I found it's not difficult to fit in the current workflow.

Now, you can:

1. open online file by `o o` in hydra menu (input online url)
2. then, all things behave like local file: you can change the speed or volume, seek forward or backward, insert either timestamp link or A-B loop link, go to the right position by clicking link!

I have only tested on bilibili (example url: https://www.bilibili.com/video/BV16t411n7vJ), it's not easy for me to test youtube video because of GFW, but I think this should work for all platforms supported by mpv.

Have a try and I'm looking forward to your response ;D

**Comment by japhir** [comment]
Wow it's great that you immediately attempted implementing this! Thanks!

I'm not sure if I understand how it's supposed to function: should clicking/C-c o'ing on a `video:https://video-url` work? If I call `org-media-note-hydra/body` directly and then <kbd>o</kbd>, it asks me for a file to play and I don't know how to give it the url. Perhaps because I'm using ivy/counsel?

**Comment by japhir** [comment]
Perhaps this is an issue on my end, when I call the back-end function `(mpv-play "https://www.bilibili.com/video/BV16t411n7vJ")` it doesn't do anything except echo `t`.

**Comment by japhir** [comment]
Hmm whoops, looks like I wasn't loading the newest file! sorry about that, it seems to work now when I enter the hydra/body and open the url manually. Opening up the video org-links with timestamps also appears to work, also for youtube!

**Comment by yuchen-lea** [comment]
That's normal, since currently there're only 2 kinds of links are supported: Timestamp Link and A-B Loop Link. you can find more info in Readme.

The `split-string` error is because your self-made [[video:url]] links are not supported. They should be something like `video:url#timestamp`. You can easily insert the correct format in hydra menu (search `org-media-note-insert-link` in readme), self-made is not recommended.

**Comment by japhir** [comment]
Ah ok, I expected a link without any timestamps to just open it at timestamp 0! So I can make notes by:
- add a link to a video I want to make notes for, video:url
- open it with a simple C-c o or <ret>
- hit i to make a timestamp note

**Comment by yuchen-lea** [comment]
I'm going to close the issue since remote video streaming is supported now.

Currently, I can't see the value of links like video:url. If you want to make notes for some video, why not use `o o` or `o l` to open them and make notes then? 

If you think [adding a video:url link and opening it] has more advantages, please open an new issue and describe the situation.

**Comment by japhir** [comment]
Great! Thanks so much!
In the cases where I do want to create a manual URL, I can just append `#0` to start at the beginning, so that's fine! :)
