### ISSUE TITLE
why we need "formats" field

### ISSUE THREAD

**Issue by emacsbliss** [yuchen-lea/org-media-note#15]
it looks like my bib file has no `formats` field for the video entry. (I'm using Zotero and better bibtex to export bib file).

In fact looking at the code, I'm not sure why we need the `formats` field.
Basically we already have the file from bib file, from it I think we can extract the extension
and use that as format to proceed..

not sure why there is no formats fields exported, I do set `format` field in Zotero..

**Comment by yuchen-lea** [comment]
Emm... personally, I use calibre to export bib. There're `formats` field in it.

Of course, we can get the extension from `file` filed directly. The reason why I use `formats` field is because:
1. There already exsists`bibtex-completion-find-pdf`, which could get file path and handle many exceptions well.
2. However, there is one problem: if there're multiple files in `file` fields, it will only return the first file. If video is not  in the first place, things go wrong.
3. I don't want to write a duplicate function do the `bibtex-completion-find-pdf` work. So I combined the result of `bibtex-completion-find-pdf` and the result of `format` field, to make sure it could find the media file in the multiple files situation. 
4. Also, for calibre,  all files of the same bib entry have the same file name, only the extensions differ.

It works well for the calibre exported bib files. But I haven't considered other situation.

I don't know how zotero export bib files, I want to know:
1. Have you tried  Better BibTeX for Zotero? Can this export format field? [Extra fields :: Better BibTeX for Zotero](https://retorque.re/zotero-better-bibtex/exporting/extra-fields/ "Extra fields :: Better BibTeX for Zotero")
2. Is it possible for zotero to have more than one files for one bib entry? 
3. If the answer is yes, could they have completely different file names? Please show me the most complicated bib entry.

**Comment by yuchen-lea** [comment]
After brief investigation, I found: It's possible for zotero to have more than one files for one bib entry, and they colud be completely different file names. Also, bibtex could extract multiple files from zotero bib, but only one from calibre bib.

Current design is not general, I will look into `bibtex-completion-find-pdf`. This function is beyond my ken, I'm not famillar with many functions in it, it may take some time.

**Comment by yuchen-lea** [comment]
Zotero bib should work now. 

There're some problems with Calibre bib now, because bibtex could extract only one file from calibre bib. I'm going to  create a PR for bibtex, then everything will work.

**Comment by emacsbliss** [comment]
great, thanks a lot for improving it.

I gave another try and now video can start play!!

however discovered few more issues and I created https://github.com/yuchen-lea/org-media-note/pull/16 to fix them.

now it seems all working!! thanks again for the effort to create this package.
