### ISSUE TITLE
error "Failed to connect to mpv")

### ISSUE THREAD

**Issue by AtomicNess123** [yuchen-lea/org-media-note#26]
I am currently getting this error when attempting to open a video file.
Any help welcome. Thanks!

**Comment by yuchen-lea** [comment]
Call `mpv-play`, chose the video file to open, and see if you can play it.

If you can't, there must be something wrong with [mpv.el](https://github.com/yuchen-lea/org-media-note/issues][error "Failed to connect to mpv") · Issue #26 · yuchen-lea/org-media-note).

**Comment by yuchen-lea** [comment]
It seems to be the issue of mpv.el, and you found the better place to handle this kljohann/mpv.el#18 . I'm going to close this issue.

**Comment by thiessenstuart** [comment]
It would be nice if you would warn Windows users that your extension doesn't work because mpv.el doesn't work so that we don't go through all the work of installing your software only to find it doesn't work. It's kind of frustrating that no one wants to do something about it.

The best people to figure it out are the people who wrote the code in the first place. Isn't there a way you can collaborate with kljohann to figure out a solution so that your shared users have a solution? I'm not a Lisp programmer or I would be happy to help. I could test solutions if that would be helpful.
