### ISSUE TITLE
Allow the capture and use of milliseconds

### ISSUE THREAD

**Issue by nanjigen** [yuchen-lea/org-media-note#27]
I'm finding I need fainer-grained controls in certain kinds of video. Specifically `org-media-note` doesn't seem to respond to or capture increments in the milliseconds. Some frames are quite different and yet only be 0.1s apart. 

Would it be possible to allow for the hydra to display milliseconds and have mpv respond to millisecond increments? Of course, the link format would have to allow for a full timestamp `0:00:00:00/h:mm:ss:ff` <- there might have to be legacy code to allow for backward compatibility with the older link style if this were done. 

What do you think?

**Comment by yuchen-lea** [comment]
I use format `h:mm:ss.fff` since it seems to be the standard ([How to: Display Milliseconds in Date and Time Values | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-display-milliseconds-in-date-and-time-values)).

You can toggle the timestamp format between `h:mm:ss` and `h:mm:ss.fff` in hydra menu:
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/7555085/128644041-8bed9b01-d84c-4ee6-81f3-0ac8f448ecad.png">

Once, changed to `h:mm:ss.fff`, all things should work like before: insert link, insert ab loop link, follow link, etc.

I didn't test a lot. Tell me if there're any problems.
