### ISSUE TITLE
Completion support for videocite link with org-ref

### ISSUE THREAD

**Issue by promisedlandt** [yuchen-lea/org-media-note#30]
Hello Yuchen,

using org-ref, I have completion support for `cite:` links, with ivy-bibtex. But I have no completion support for `audiocite` or `videocite`.
Do you have any hint on how to set it up?

**Comment by yuchen-lea** [comment]
I think the workflow is a little different from org-ref: In org-ref, we insert the citation key. In org-media-note, we insert the media file and the timestamp.

Thus, the basic workflow:
1. open the media file using mpv
2. insert current timestamp, screenshot, subtitle, etc.

In step 1, you can:
1. manually find a media file
2. open the file which is the file of a citation key

Then, the question is, which citation key? By default, org-media-note will find the key stored in `Custom_ID` property of current heading and auto open the corresponding file if you call `org-media-note-mpv-smart-play`. You can also customize the field name by `org-media-note-ref-key-field`.

My usual workflow:
1. create a note by `org-ref-notes-function`, this will creates a note like (depends on your note template):
  

> ** 01 introduction (part 1)
>     :PROPERTIES:
>     :Custom_ID: course.957
>     :AUTHOR:   Michael Collins
>     :END:
> 
> cite:course.957
> 

2. call `org-media-note-mpv-smart-play` under this heading will auto open the mp4 file, because the bib entry records the media file location:

> @misc{ course.957,
>     title = "01 Introduction (Part 1)",
>     author = "Michael Collins",
>     formats = "mp4, pdf",
>     file = ":/Users/yuchen/Courses/Michael Collins/01 Introduction (Part 1) (957)/01 Introduction (Part 1) - Michael Collins.mp4:MP4, :/Users/yuchen/Courses/Michael Collins/01 Introduction (Part 1) (957)/01 Introduction (Part 1) - Michael Collins.pdf:PDF",
>     custom_duration = "11",
>     series = "[COMS W4705]Natural Language Processing.01 Week 1 - Introduction to NLP",
>     volume = "1"}
> 

3. make media notes ;)

**Comment by promisedlandt** [comment]
Thank you very much for the detailed description. It's not what I want to do, but I understand much better how it is intended to be used now.
Everything with org-media-note works great, it's the steps before where I can not do what I want :smile:
