### ISSUE TITLE
Add time-range timestamp

### ISSUE THREAD

**Issue by nanjigen** [yuchen-lea/org-media-note#5]
I'm envisioning extending the timestamps to include an optional time range. For example:
`[[video:course.mp4#a<0:01:55>b<0:02:10>][0:01:55-0:02:10]] This is an example of a 15s loop from 1m55s to 2m10s`

Maybe we could then cause `org-media-note` to treat the range as a [loop](https://mpv.io/manual/stable/#options-ab-loop-a), which is called via cmd as `--ab-loop-a=<time>, --ab-loop-b=<time>`. Aside from declaring a snippet of video where something is discussed/occurs, there may be uses on the `mpv` end in terms of extracting or acting upon the loop with `lua`, as [many scripts do](https://github.com/occivink/mpv-scripts). Moving cursor to point in the `org` buffer could then optionally allow (maybe based on a `setq`), the automatic looping of that time range.

**Comment by yuchen-lea** [comment]
ab-loop is a good idea! It's supported now although the link format is a little different from your design:

1. ab-loop link format `[[video:course.mp4#0:01:55-0:02:10][desc]]`
2. desc is customized by `org-media-note-ab-loop-link-format`, default is `0:01:55-0:02:10`
3. when mpv is playing media in ab loop, then insert ab-loop link instead of timestamp link
4. click ab-loop link will jump to point a and loop between a and b

I'm not sure I understand the scripts part. Seems that you can add customized actions to link?

**Comment by nanjigen** [comment]
This works beautifully, thank you for the speedy response and implementation! The link format is perfect and the added hydra heads was an unexpected bonus, great work

In terms of the `lua` scripts mention, I only meant to point out that `mpv` users might write scripts that act on the A-B loop; like extracting that portion of the video and converting to `gif` or `webm`. This plugin and `mpv` make many things possible!

**Comment by yuchen-lea** [comment]
Got it! Happy to hear that you enjoy it!

Please let me know if you have any question. ;D
