### ISSUE TITLE
Home folder video: links

### ISSUE THREAD

**Issue by nanjigen** [yuchen-lea/org-media-note#7]
Normal `file` links in `org` use the tilde dash prefix `~/`, but for `org-media-note` `video:` links; the full path is included instead, breaking links across systems with different usernames: 
`video:/home/nanjigen/Videos/movie.mp4` vs the preferred `video:~/Videos/movie.mp4`.

Also, at least for me, using insert `i` to insert a timestamp creates a link with the prefix `nil` instead of `video`; which means I need to repair the link by hand - other than these two issues once edited the links work great

**Comment by yuchen-lea** [comment]
I mainly use videoref link, so I don't need to dealt with the video path. For your situation and a general way, I'm not sure which is better:

1. substitue `/home/nanjigen` to `~`
2. change the absolute file path to relative path,  which is interpreted relative to the directory of org file

`nil` prefix is really really an awful experience. I guess that's because `org-media-note--video-types` and `org-media-note--audio-types` didn't contain your media file type. What's your media file type (extension) ?

**Comment by nanjigen** [comment]
Thanks `yuchen`. I believe there is a built-in for this, have a look at `org-link-file-path-type`. I currently have mine set to `adaptive` (I believe this is default on Doom) and it produces the `'absolute'` path option with `~`.

As for my video type, the video is `.mpg`. This is related to [#6](https://github.com/yuchen-lea/org-media-note/issues/6#issuecomment-782479406), adding `mpg` to `org-media-note--video-types` fixes the `nil:` link prefix, but not the `attach-dir` issues with that filetype mentioned in #6

**Comment by yuchen-lea** [comment]
Thanks for telling me about `org-link-file-path-type`. Although it can't be used directly, but it's not difficult to keep consistent with it. Now, the media link and screenshot link should be the format set by `org-link-file-path-type`. Check the doc for more info.

It works well on my computer, hope it also works for you :D

**Comment by nanjigen** [comment]
This works great for me too, thanks @yuchen-lea !
